# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Lirui Guo
first_name: Lirui
middle_name:
last_name: Guo
email: Lirui.Guo@monash.edu
linkedin: lirui-guo
google_scholar: 13uW1k0AAAAJ

contact_note: >
  You can contact me via email.

description: >
  PhD Candidate in Civil and Environmental Engineering at Monash University. 

footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

keywords: intelligent transport systems, human-AI interaction, business analytics, shared autonomous vehicles, Monash University

lang: en
icon: ⚛️

url: https://lirui3.github.io
baseurl: ""
last_updated: false
